### ISSUE TITLE
Figure out the back end of AnomalyDetection

### ISSUE THREAD

**Issue by mramakrishnan-chwy** [egovernments/analytics#168] opened 2017-02-19 09:46 UTC
- Does the window size matter in detecting the anomalies?
- How do we select the optimal values of _alpha_ and _max_anoms_ ?
- What does the parameter _longterm_ mean?

**Comment by samarthbhargav** [comment] 2017-03-19 16:42
Duplicate of #162 , closing.

**Closed as completed by samarthbhargav** 2017-03-19 16:42 UTC
Labels: alerts, r-lib
